language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-dev libbluetooth-dev

script:
  - aclocal
  - autoconf
  - ./configure
  - make
  - sudo make install
  - PYTHON_VERSION=$(python3 -c 'import sys; print(sys.version[:3])')
  - PYTHONPATH=/usr/local/lib/python${PYTHON_VERSION}/site-packages python3 -c 'import cwiid' 
